/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process
precacheAndRoute(self.__WB_MANIFEST);

// Cache the Google Fonts stylesheets with a stale-while-revalidate strategy
registerRoute(
    /^https:\/\/fonts\.googleapis\.com/,
    new StaleWhileRevalidate({
        cacheName: 'google-fonts-stylesheets',
    })
);

// Cache the underlying font files with a cache-first strategy for 1 year
registerRoute(
    /^https:\/\/fonts\.gstatic\.com/,
    new CacheFirst({
        cacheName: 'google-fonts-webfonts',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
                maxEntries: 30,
            }),
        ],
    })
);

// Cache images
registerRoute(
    /\.(?:png|gif|jpg|jpeg|webp|svg)$/,
    new CacheFirst({
        cacheName: 'images',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// Cache JavaScript and CSS
registerRoute(
    /\.(?:js|css)$/,
    new StaleWhileRevalidate({
        cacheName: 'static-resources',
    })
);

// Cache weather API responses
registerRoute(
    /\/api\/weather/,
    new NetworkFirst({
        cacheName: 'weather-api',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 5 * 60, // 5 minutes
            }),
        ],
    })
);

// Fallback for document requests
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new RegExp('/[^._]+');
registerRoute(navigationRoute, handler);

// Handle offline fallback
self.addEventListener('fetch', (event) => {
    if (event.request.mode === 'navigate') {
        event.respondWith(
            fetch(event.request).catch(() => {
                return caches.match('/offline.html');
            })
        );
    }
});

// Handle background sync for calculations
const CALCULATION_SYNC_TAG = 'calculation-sync';

interface CalculationTask {
    id: string;
    data: any;
}

self.addEventListener('sync', (event) => {
    if (event.tag === CALCULATION_SYNC_TAG) {
        event.waitUntil(syncCalculations());
    }
});

async function syncCalculations() {
    try {
        const cache = await caches.open('calculation-queue');
        const requests = await cache.keys();
        
        await Promise.all(requests.map(async (request) => {
            const response = await cache.match(request);
            if (!response) return;
            
            const task: CalculationTask = await response.json();
            
            try {
                const result = await fetch('/api/calculate', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify(task.data),
                });
                
                if (result.ok) {
                    await cache.delete(request);
                }
            } catch (error) {
                console.error('Failed to sync calculation:', error);
            }
        }));
    } catch (error) {
        console.error('Failed to process sync queue:', error);
    }
}

// Handle push notifications
self.addEventListener('push', (event) => {
    const data = event.data?.json();
    
    const options = {
        body: data.body,
        icon: '/icons/icon-192x192.png',
        badge: '/icons/badge-72x72.png',
        data: data.url,
        actions: [
            {
                action: 'view',
                title: 'View Details',
            },
        ],
    };
    
    event.waitUntil(
        self.registration.showNotification(data.title, options)
    );
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    
    if (event.action === 'view' && event.notification.data) {
        event.waitUntil(
            clients.openWindow(event.notification.data)
        );
    }
});
